sudo: false
notifications:
  email: false
branches:
  only:
    - master
language: node_js
node_js:
  - "10"
install:
  - npm install -g npm@2
  - npm install -g webpack-cli
  - npm install -g webpack
script:
  - npm run build